from ROOT import *
import sys,os

if __name__ == "__main__":

    histo = TH1D('SummaryMeanCurrents','',4,0,4)
    histo.SetBinContent(1,3.62)
    histo.SetBinError(1,0.34)
    histo.SetBinContent(2,3.06)
    histo.SetBinError(2,0.25)
    histo.SetBinContent(3,3.48)
    histo.SetBinError(3,0.21)
    histo.SetBinContent(4,0.99)
    histo.SetBinError(4,0.17)

    histo1 = TH1D('SummaryRMSCurrents','',4,0,4)
    histo1.SetBinContent(1,2.06)
    histo1.SetBinError(1,0.24)
    histo1.SetBinContent(2,1.46)
    histo1.SetBinError(2,0.18)
    histo1.SetBinContent(3,1.24)
    histo1.SetBinError(3,0.15)
    histo1.SetBinContent(4,1.03)
    histo1.SetBinError(4,0.12)

    c1 = TCanvas()
    gStyle.SetOptStat(0)
    histo.SetMarkerStyle(21)
    histo.SetMarkerColor(2)
    histo.SetMarkerSize(2)
    c1.SetTickx(1)
    c1.SetTicky(1)
    xaxis = histo.GetXaxis()
    xaxis.SetBinLabel(1,'Disk +1')
    xaxis.SetBinLabel(2,'Disk +2')
    xaxis.SetBinLabel(3,'Disk +3')
    xaxis.SetBinLabel(4,'Disk +4')
    yaxis = histo.GetYaxis()
    yaxis.SetTitle('Mean Current #mu A')
    histo.Draw()
    c1.SaveAs('plots/MeanCurrent.png')


    histo1.SetMarkerStyle(21)
    histo1.SetMarkerColor(2)
    histo1.SetMarkerSize(2)
    c1.SetTickx(1)
    c1.SetTicky(1)
    xaxis = histo1.GetXaxis()
    xaxis.SetBinLabel(1,'Disk +1')
    xaxis.SetBinLabel(2,'Disk +2')
    xaxis.SetBinLabel(3,'Disk +3')
    xaxis.SetBinLabel(4,'Disk +4')
    yaxis = histo1.GetYaxis()
    yaxis.SetTitle('RMS Current #mu A')
    histo1.Draw()
    c1.SaveAs('plots/RMSCurrent.png')
